name: CMake

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Linux"
            os: ubuntu-latest
            cmake: '-G "Ninja Multi-Config" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++'
          - name: "Mac"
            os: macos-latest
            cmake: '-G "Ninja Multi-Config" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++'

    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}

    steps:
    - uses: actions/checkout@v2
      with:
          lfs: true
          submodules: recursive
    - uses: actions/setup-python@v2.2.1 # Get Python3
    - uses: egor-tensin/setup-clang@v1  # Get Clang
      if: startsWith(runner.os, 'macos')
    - uses: lukka/get-cmake@v3.19.2     # Get CMake and Ninja
      
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -B build ${{matrix.config.cmake}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/dxc $(cat ${{github.workspace}}/utils/cmake-predefined-config-params)
      
    - name: Build Release
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build build --config Release
      
    - name: Install Release
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build build --config Release
      
  # - name: Package Release
  # - name: Upload Release
       
